language: objective-c

branches:
  except:
    - gh-pages

osx_image: xcode11

env:
  global:
    - FRAMEWORK_NAME="Tabman"
    - UPDATE_DOCS="true"

before_install:
- export HOMEBREW_NO_AUTO_UPDATE=1
- brew outdated carthage || brew upgrade carthage
- bundle install

#before_script:
#- bundle exec danger

script:
- .scripts/build

after_success:
  - bash <(curl -s https://codecov.io/bash) -J Tabman
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    .scripts/update-gh-pages

notifications:
  email: false